name: Run code checks

on:
  pull_request:

  push:
    branches:
      - master

jobs:
  checks:
    runs-on: ubuntu-latest
    name: Check code style
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        shell: bash
        run: |
          yarn install

      - name: Check format
        shell: bash
        run: |
          yarn ci

  build:
    runs-on: ubuntu-latest
    name: Check if build works
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        shell: bash
        run: |
          yarn install

      - name: Build
        shell: bash
        run: |
          yarn build
